### ISSUE TITLE
Organize the documentation regarding the developers activities.

### ISSUE THREAD

**Issue by iGormilhit** [rero/developer-resources#11]
The project has a TOC, but it's not always easy to understand what the main topic of each section. Matter of fact, it's not even easy to understand what is this project. This could be improved.

**Comment by blankoworld** [comment]
I think that all README.md in each section is redundant.
Why are there here?

Is that not enough to add a main README.md with direct link to each howto?

**Comment by iGormilhit** [comment]
@blankoworld You are right. But in this issue I'm thinking about the main `README.md` at the root of the project. I think that a short description of each section could be useful.

**Comment by iGormilhit** [comment]
This issue is larger than that. This documentation needs to be organized, with section according to activities, and sections descriptions. So, I'm rewriting the issue title.
